services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: notepad-backend
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
